### PR TITLE
Doc/format docs

### PR DESCRIPTION
**Pull request by matthew-n**
Kicking off some initial documentation.

I'm looking to replace the excel file with the Markdown and or the CSV.

any opinions about keeping the CSV and generating the markdown(s) from it when changed?

### CODE REVIEW

**Comment by tcartwright** [comment]
I am fine with killing the CSV. Although I did find this: https://tabletomarkdown.com/convert-spreadsheet-to-markdown/

**Comment by tcartwright** [comment]
I actually think writing some script to convert the CSV to markdown may be another alternative. What do you think?

**Comment by delgertome** [comment]
I think an initial conversion via a script makes sense. Some data would have to be filled in later like a human readable name for a ToC, etc. I was talking to Matt earlier and thought this format would look good ("Please forgive any bad SQL as I wrote it off the cuff," he says to two judgey DBAs.):

## Performance

### SRP0001 - Avoid Nested Views

#### Description
Views should not use other views as a data source

#### Notes
Ignorable: No
Other important data to be added manually.

#### Examples
```tsql
-- Bad
CREATE VIEW last_twenty_four AS
SELECT table1_id, modified_date FROM table1 WHERE modified_date > DATEADD(day, -1, SYSDATETIME());
GO

CREATE VIEW ids_of_last_twenty_four AS
SELECT table1_id FROM last_twenty_four;
GO
```

```tsql
-- Good
CREATE VIEW last_twenty_four AS
SELECT table1_id, modified_date FROM table1 WHERE modified_date > DATEADD(day, -1, SYSDATETIME());
GO

CREATE VIEW ids_of_last_twenty_four AS
SELECT table1_id FROM table1 WHERE modified_date > DATEADD(day, -1, SYSDATETIME());
GO
```

**Comment by tcartwright** [comment]
I can write some powershell to extract the markdown from comments in the C# file. I have done it before for another project. Will just have work on it when I get time. 

I like the example, looks nice.

**Comment by delgertome** [comment]
I actually have some time tonight. I can take it up.

**Comment by tcartwright** [comment]
> I actually have some time tonight. I can take it up.

@delgertome you want to work on the powershell script to extract c# comments?

**Comment by delgertome** [comment]
Ah, I started writing it to extract the CSV into Markdown. I misunderstood.

Is there a difference between the two?

**Comment by tcartwright** [comment]
> Ah, I started writing it to extract the CSV into Markdown. I misunderstood.
> 
> Is there a difference between the two?

We were talking about getting rid of the CSV, and going straight to the C# to extract the info. We could pull everything above from the attributes, except for the examples. I believe we would have to write those in the C# header comments.

I like the idea of extracting it from the C#, and getting rid of the intermediate step of the CSV.

How about I start the powershell tomorrow, and you can finish it off?

**Comment by delgertome** [comment]
That makes sense and works.

**Comment by matthew-n** [comment]
replaced with #18

**Pull request closed without merging**
